- name: Deploy to Itch.io
        uses: josephbmanley/butler-publish-it-action@master
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: html
          ITCH_GAME: cannons024willrise/laserchess
          ITCH_USER: cannons024willrise
